# Generated by Django 4.2.4 on 2023-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FifthSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=250, null=True)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('s_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('t_img', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='FirstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=250, null=True)),
                ('two', models.CharField(blank=True, max_length=250, null=True)),
                ('three', models.CharField(blank=True, max_length=250, null=True)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('s_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('t_img', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='FourthSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=250, null=True)),
                ('two', models.CharField(blank=True, max_length=250, null=True)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('s_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('t_img', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('gmail', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=250, null=True)),
                ('two', models.CharField(blank=True, max_length=250, null=True)),
                ('three', models.CharField(blank=True, max_length=250, null=True)),
                ('four', models.CharField(blank=True, max_length=250, null=True)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='SixSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=250, null=True)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('s_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('two', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=250, null=True)),
                ('two', models.CharField(blank=True, max_length=250, null=True)),
                ('three', models.CharField(blank=True, max_length=250, null=True)),
                ('four', models.CharField(blank=True, max_length=250, null=True)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('s_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('t_img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('fo_img', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
