# Generated by Django 4.2.4 on 2023-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsection',
            name='fi_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='fp_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='firstsection',
            name='si_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
