# Generated by Django 4.2.4 on 2023-08-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0002_firstsection_fi_img_firstsection_fp_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstsection',
            old_name='fp_img',
            new_name='fo_img',
        ),
        migrations.RemoveField(
            model_name='firstsection',
            name='t_img',
        ),
    ]
