# Generated by Django 4.2.1 on 2023-08-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0004_remove_thirdsection_four_remove_thirdsection_three_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourthsection',
            name='fo_img',
        ),
    ]
