# Generated by Django 4.2.1 on 2023-08-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0005_remove_fourthsection_fo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='gmail',
            new_name='email',
        ),
    ]
