# Generated by Django 4.2.1 on 2023-08-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0006_rename_gmail_questions_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
