# Generated by Django 4.2.1 on 2023-08-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0007_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.FileField(upload_to='video')),
            ],
        ),
    ]
